### ISSUE TITLE
Navbar Capitalization Inconsistency

### ISSUE THREAD

**Issue by seanposton4** [WebAssembly/website#329]
On the navbar for `https://webassembly.org/`, there is a capitalization inconsistency with "Getting Started" and "Future features". I assume the latter should be "Future Features," unless this is intentional.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/26977519/228907975-f1415656-ba4f-4245-a023-685962f397b8.png">

**Comment by dschuff** [comment]
Actually, I think there's a bigger issue, which is that the purpose of the page has expanded such that it covers both current and future features, and the most useful feature of the page is around features that are already implemented; so I think neither "future features" or "Roadmap" is the best name for the page in the first place. Rather than hijack this issue, maybe I'll file a new issue or a PR to fix that...
