### ISSUE TITLE
/r/webassembly has permanently closed

### ISSUE THREAD

**Issue by mikestaas** [WebAssembly/website#341]
the webassembly subreddit has been shut down, the link should be removed from https://webassembly.org/community/resources/

as an aside this was a great forum to discuss webassembly, it would be great if we could find a replacement

**Comment by Robbepop** [comment]
Is there information on why the subreddit for WebAssembly has closed? Is there a chance to revive it somehow with new volunteers for moderation? I think it was a great resource for news about Wasm.

**Comment by MileyFu** [comment]
Yes. Why though? Is there a way to create a new one? Or some kind of ownership transfer😢

**Comment by mikestaas** [comment]
i also reached out to the moderator to ask why it was shuttered and received no response

**Comment by Robbepop** [comment]
@mikestaas @MileyFu today I created a new WebAssembly subreddit here: https://www.reddit.com/r/WebAssembly2/
Unfortunately I was not allowed to revive the former `r/Wasm` and `r/WebAssembly` due to missing experience as Reddit moderator but maybe we will get there one day.

The new subreddit is still under review which probably will take a week or so until fully reviewed by Reddit standards. Help, advise and feedback is welcome!

**Comment by MileyFu** [comment]
Joined. Maybe can get some more to join by telling WasmCon folks. Count me in when need more moderators🙏

**Comment by Robbepop** [comment]
Thanks! Do you already have experience being a Reddit mod? For me it is the first time, so I don't have a clue what I am getting myself in haha.
Would be great if we could spread the word about this new subreddit on WasmCon, unfortunately I won't be there in person.

**Comment by dschuff** [comment]
If the old subreddit doesn't seem to have a near-term prospect of reactivating, we should probably remove it from the website. If you're committed to moderating, I could just update the link to r/WebAssembly2? We can always take it down or switch back in the future.

**Comment by dschuff** [comment]
I guess I'm showing my ignorance of Reddit here, but do r/wasm and r/webassembly just exist because they were started by different people who didn't talk to each other? If we start r/webassembly2, will it be possible to merge or migrate the subreddits in the future, or will we just be stuck with further fragmentation?

**Comment by Robbepop** [comment]
I cannot tell you either how both `r/wasm` and `r/webassembly` came to existance.

- `r/webassembly`: was more active and had roughly 15k members
- `r/wasm`: was pretty much inactive and had only roughly 5k members from what I remember

However, I think both subreddits were hosted by the same set of people since both subreddits closed down at the same time without explanation or forewarning to the WebAssembly community.

There is a process at Reddit to take over inactive or closed subreddit which is what I tried to do with both subreddits. However, as described earlier I was denied due to missing experience as a Reddit moderator.

So my hope is that in the future we can finally take over both `r/wasm` and `r/webassembly` and then either move over to `r/webassembly` or ideally re-link all 3 subreddits to the same source.
