### ISSUE TITLE
Add visual asm.js indicator to Tanks! demo

### ISSUE THREAD

**Issue by s3ththompson** [WebAssembly/website#84]
Underneath the demo `<canvas>` element, there should be an indication if WebAssembly isn't supported and the asm.js fallback is used.

**Comment by jfbastien** [comment]
![horse](https://cloud.githubusercontent.com/assets/298127/23686088/6cbbc7d6-035c-11e7-8653-6f477af1b3c5.png)

**Comment by RobertoMalatesta** [comment]
Btw, tanks demo is not working on FF 52 Kubuntu 14.04 and on the nightly build.
It plays the music and shows a full brown landscape.
The demo is correctly working on Chromium Nightly and Chrome 53.

It's not something configuration based since angrybot has always been running and FF 52 correctly runs
@floooh  examples at [http://floooh.github.io/oryol-samples/](http://floooh.github.io/oryol-samples/)

-- Rob

**Comment by titzer** [comment]
On Wed, Mar 8, 2017 at 4:17 PM, Roberto Malatesta <notifications@github.com>
wrote:

> Btw, tanks demo is not working on FF 52 Kubuntu 14.04 and on the nightly
> build.
> It plays the music and shows a full brown landscape.
> The demo is correctly working on Chromium Nightly and Chrome 53.
>
Probably should not work on Chrome 53, unless it's asm.js. Chrome 57 is the
first Chrome version that fully supports WASM version 0x1. Can you double
check?

**Comment by lukewagner** [comment]
@RobertoMalatesta If it runs but but shows incorrect output (brown landscape, but I'm guessing nothing else?) sounds like it could be a WebGL problem, possibly driver related.  It'd be helpful to [file a bug in the Canvas:WebGL component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core) including the contents of `about:support`.

**Comment by RobertoMalatesta** [comment]
@titzer wasm was available on Chrome 53.x as well through chrome flags see:
![bug335](https://cloud.githubusercontent.com/assets/11835025/23711672/cd06bf1e-0420-11e7-9088-d0b3619b67e9.jpg)
![bug334](https://cloud.githubusercontent.com/assets/11835025/23711681/d39e42e8-0420-11e7-8398-1b4915a34658.jpg)

It's true that it should have a different major, but the demo boot page seems to like it (when not  the page shows a fallback into emscripten/asm red message instead of play webassembly):
![bug337](https://cloud.githubusercontent.com/assets/11835025/23711758/11654f54-0421-11e7-9ce8-bd01c1931201.jpg)

It definitely runs on **Version 59.0.3032.0 (Developer Build) (64-bit)** (I can say it's wasm because emscripten plays the sounds, wasm uses a codec missing on chromium).

And file served both to 53 and 59 are the same.

-- Rob

**Comment by titzer** [comment]
Ok, I am not sure if the Tanks demo does the version testing that the AngryBots demo did. @s3ththompson?

**Comment by RobertoMalatesta** [comment]
@lukewagner you guessed right:

![bug338](https://cloud.githubusercontent.com/assets/11835025/23712931/9e0dd658-0424-11e7-889a-05285487398f.jpg)

Definitely is a problem with the NVIDIA Card / Driver FF has (but then, other demos I posted before and my own tests run smoothly_)

I just tested FF 52 on an older machine with an Intel Card (Opengl 2.1, go figure) and the demo visualizes correctly.

-- Rob

**Comment by RobertoMalatesta** [comment]
... or maybe it's unity.
Cannot we sport some simpler demos ?

**Comment by jfbastien** [comment]
@RobertoMalatesta does the asm.js version of the demo work on the machine where it fails for wasm?

**Comment by floooh** [comment]
...simpler demos? (hint, hint) ;) http://floooh.github.io/oryol-samples/ 

They default to asm.js though when clicking on the screenshots though.

I feel (while the UE4 and Unity demos certainly look very impressive), the big downloads and long startup times of those demos don't help much when trying to convince 'decision makers' in the gaming industry to invest in the technology, at least from my point of view (which is coming from browser and mobile games, not 'AAA').

I've had some discussions with Chinese colleagues a few months ago about mobile HTML5 games on WeChat (basically what Facebook is now also trying with Instant Games). These games must be small and start within a few seconds. The Chinese team I spoke have been doing simple 2D sprite games with JS/Typescript engines so far, and now want to also bring simple 3D games to WeChat but they are hitting various limits with those existing JS engines. For native mobile games they are using Unity, but with 3..5 MByte just for 'executable' this is way too big for WeChat. When I showed them that it is possible to create simple 3D clients in under 500 KBytes with a small C++ engine like Oryol they basically couldn't believe what they're seeing.

Just my 2ct :)

**Comment by RobertoMalatesta** [comment]
@jfbastien  Negative for release 52.
But _positive_ for **firefox-55.0a1.en-US.linux-x86_64** the nightly work flawlessly **both** with wasm enabled and disabled.
Oh, a _minor_ issue for the nightly is that while changing the 2 wasm defaults and closing it quickly it crashed wiping away its whole directory content. :rofl: 


--Rob

**Comment by RobertoMalatesta** [comment]
@floooh 

> ...simpler demos? (hint, hint) ;) http://floooh.github.io/oryol-samples/

I mantioned you in this thread on purpose.


> When I showed them that it is possible to create simple 3D clients in under 500 KBytes with a small C++ engine like Oryol they basically couldn't believe what they're seeing.

I confirm this (take out iostreams and other C++ fat and you go 400k unzipped).

Too bad we still don't have a complete UI (and pThreads and sockets) since I'd have switched all my code to
emscripten/wasm.
Having native+web in a single shot is a big bonus.

BTW: Typescript + Canvas/WebGL is not sooo bad.

--Rob

**Comment by s3ththompson** [comment]
@titzer @RobertoMalatesta WebAssembly compat testing on the overview page is much simplified over previous version. Just `typeof WebAssembly === 'object'`. Technically this could be a false positive for previous experimental versions of WebAssembly, but these will soon disappear and it's preferable to keep compact code succinct going forward. (Tanks! itself has additional logic; also requires `WebAssembly.validate` and `WebAssembly.compile` to be functions, otherwise it falls back transparently to asm.js.)

@floooh 👍  Trying to figure out how to accommodate more than one demo on this page in a scalable fashion (and accept community contributions). Would love to feature Oryol

**Comment by kripken** [comment]
Another possible demo for a list, if we add one, is [BananaBread](https://kripken.github.io/BananaBread/cube2/bb.html).

**Comment by jfbastien** [comment]
@s3ththompson I like how https://d3js.org/ does it.

**Comment by binji** [comment]
Closing since the demo is now removed.
